name: Provision NYT

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 6 * * *' # runs every day at midnight Mountain Daylight Time (UTC-6)

jobs:
  provision:
    runs-on: macos-latest
    
    env:
      LIBRARY_CARD_NUMBER: ${{ secrets.LIBRARY_CARD_NUMBER }}
      LIBRARY_NAME: ${{ vars.LIBRARY_NAME }}
      NYT_USERNAME: ${{ secrets.NYT_USERNAME }}
      NYT_PASSWORD: ${{ secrets.NYT_PASSWORD }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Provision Base Subscription
      run: python provision_nyt.py

    - name: Provision Games Subscription
      run: python provision_nyt.py games
    
    - name: Provision Cooking Subscription
      run: python provision_nyt.py cooking